App:
  RunMode: debug
  ReadTimeout: 60
  WriteTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  UserName: hong
  Password: cwb+123
  Host: 127.0.0.1
  DBName: DistributedLocks
  TablePrefix: lock_
  Charset: utf8
  ParseTime: True
  MaxLifeTime: 10
  MaxIdleConns: 10
  MaxOpenConns: 30
